/* Enumeration of general purpose registers - Header */

#ifndef VMCU_REGISTER_H
#define VMCU_REGISTER_H

typedef enum {

    VMCU_REGISTER_NONE = -1,

    VMCU_REGISTER_R0,
    VMCU_REGISTER_R1,
    VMCU_REGISTER_R2,
    VMCU_REGISTER_R3,
    VMCU_REGISTER_R4,
    VMCU_REGISTER_R5,
    VMCU_REGISTER_R6,
    VMCU_REGISTER_R7,
    VMCU_REGISTER_R8,
    VMCU_REGISTER_R9,
    VMCU_REGISTER_R10,
    VMCU_REGISTER_R11,
    VMCU_REGISTER_R12,
    VMCU_REGISTER_R13,
    VMCU_REGISTER_R14,
    VMCU_REGISTER_R15,
    VMCU_REGISTER_R16,
    VMCU_REGISTER_R17,
    VMCU_REGISTER_R18,
    VMCU_REGISTER_R19,
    VMCU_REGISTER_R20,
    VMCU_REGISTER_R21,
    VMCU_REGISTER_R22,
    VMCU_REGISTER_R23,
    VMCU_REGISTER_R24,
    VMCU_REGISTER_R25,
    VMCU_REGISTER_R26,
    VMCU_REGISTER_R27,
    VMCU_REGISTER_R28,
    VMCU_REGISTER_R29,
    VMCU_REGISTER_R30,
    VMCU_REGISTER_R31

} VMCU_REGISTER;

#endif
