/* Enumeration of Vectors - Header */

#ifndef VMCU_VECT_H
#define VMCU_VECT_H

typedef enum {

    VMCU_VECT_NONE = -1,

    VMCU_VECT_RESET,
    VMCU_VECT_INT0,
    VMCU_VECT_INT1,
    VMCU_VECT_PCINT0,
    VMCU_VECT_PCINT1,
    VMCU_VECT_PCINT2,
    VMCU_VECT_WDT,
    VMCU_VECT_TIMER2_COMPA,
    VMCU_VECT_TIMER2_COMPB,
    VMCU_VECT_TIMER2_OVF,
    VMCU_VECT_TIMER1_CAPT,
    VMCU_VECT_TIMER1_COMPA,
    VMCU_VECT_TIMER1_COMPB,
    VMCU_VECT_TIMER1_OVF,
    VMCU_VECT_TIMER0_COMPA,
    VMCU_VECT_TIMER0_COMPB,
    VMCU_VECT_TIMER0_OVF,
    VMCU_VECT_SPI_STC,
    VMCU_VECT_USART_RX,
    VMCU_VECT_USART_UDRE,
    VMCU_VECT_USART_TX,
    VMCU_VECT_ADC,
    VMCU_VECT_EE_READY,
    VMCU_VECT_ANALOG_COMP,
    VMCU_VECT_TWI,
    VMCU_VECT_SPM_READY

} VMCU_VECT;

#endif
