#include <stddef.h>

#include "asm_table.h"
#include "handlers.h"

static asm_table_entry_t asm_table[VMCU_IID_ENUM_END] = {

    [VMCU_IID_NOP] = {

        .handler          = assemble_nop,
        .handler_unpacked = pack_and_assemble_nop,
        .n_operands       = 0,
        .n_words          = 1
    },
    [VMCU_IID_MOVW] = {

        .handler          = assemble_movw,
        .handler_unpacked = pack_and_assemble_movw,
        .n_operands       = 2,
        .n_words          = 1
    },
    [VMCU_IID_MUL]     = {

        .handler          = assemble_mul,
        .handler_unpacked = pack_and_assemble_mul,
        .n_operands       = 2,
        .n_words          = 1
    },
    [VMCU_IID_MULS]    = {

        .handler          = assemble_muls,
        .handler_unpacked = pack_and_assemble_muls,
        .n_operands       = 2,
        .n_words          = 1
    },
    [VMCU_IID_MULSU]   = {

        .handler          = assemble_mulsu,
        .handler_unpacked = pack_and_assemble_mulsu,
        .n_operands       = 2,
        .n_words          = 1
    },
    [VMCU_IID_FMUL]    = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 2, .n_words = 1 },
    [VMCU_IID_FMULS]   = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 2, .n_words = 1 },
    [VMCU_IID_FMULSU]  = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 2, .n_words = 1 },
    [VMCU_IID_LDI]     = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 2, .n_words = 1 },
    [VMCU_IID_RJMP]    = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 1, .n_words = 1 },
    [VMCU_IID_JMP]     = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 1, .n_words = 2 },
    [VMCU_IID_IJMP]    = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 0, .n_words = 1 },
    [VMCU_IID_MOV]     = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 2, .n_words = 1 },
    [VMCU_IID_DEC]     = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 1, .n_words = 1 },
    [VMCU_IID_INC]     = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 1, .n_words = 1 },
    [VMCU_IID_ADD]     = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 2, .n_words = 1 },
    [VMCU_IID_ADC]     = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 2, .n_words = 1 },
    [VMCU_IID_ADIW]    = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 2, .n_words = 1 },
    [VMCU_IID_SUB]     = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 2, .n_words = 1 },
    [VMCU_IID_SUBI]    = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 2, .n_words = 1 },
    [VMCU_IID_SBC]     = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 2, .n_words = 1 },
    [VMCU_IID_SBCI]    = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 2, .n_words = 1 },
    [VMCU_IID_SBIW]    = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 2, .n_words = 1 },
    [VMCU_IID_PUSH]    = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 1, .n_words = 1 },
    [VMCU_IID_POP]     = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 1, .n_words = 1 },
    [VMCU_IID_IN]      = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 2, .n_words = 1 },
    [VMCU_IID_OUT]     = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 2, .n_words = 1 },
    [VMCU_IID_SBIS]    = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 2, .n_words = 1 },
    [VMCU_IID_SBIC]    = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 2, .n_words = 1 },
    [VMCU_IID_SBRC]    = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 2, .n_words = 1 },
    [VMCU_IID_SBRS]    = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 2, .n_words = 1 },
    [VMCU_IID_CPSE]    = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 2, .n_words = 1 },
    [VMCU_IID_EOR]     = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 2, .n_words = 1 },
    [VMCU_IID_LDX]     = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 2, .n_words = 1 },
    [VMCU_IID_LDXI]    = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 2, .n_words = 1 },
    [VMCU_IID_LDDX]    = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 2, .n_words = 1 },
    [VMCU_IID_LDY]     = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 2, .n_words = 1 },
    [VMCU_IID_LDYI]    = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 2, .n_words = 1 },
    [VMCU_IID_LDDY]    = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 2, .n_words = 1 },
    [VMCU_IID_LDDYQ]   = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 2, .n_words = 1 },
    [VMCU_IID_LDDZQ]   = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 2, .n_words = 1 },
    [VMCU_IID_LDZ]     = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 2, .n_words = 1 },
    [VMCU_IID_LDZI]    = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 2, .n_words = 1 },
    [VMCU_IID_LDDZ]    = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 2, .n_words = 1 },
    [VMCU_IID_STX]     = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 2, .n_words = 1 },
    [VMCU_IID_STXI]    = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 2, .n_words = 1 },
    [VMCU_IID_STDX]    = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 2, .n_words = 1 },
    [VMCU_IID_STY]     = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 2, .n_words = 1 },
    [VMCU_IID_STYI]    = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 2, .n_words = 1 },
    [VMCU_IID_STDY]    = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 2, .n_words = 1 },
    [VMCU_IID_STDYQ]   = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 2, .n_words = 1 },
    [VMCU_IID_STZ]     = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 2, .n_words = 1 },
    [VMCU_IID_STZI]    = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 2, .n_words = 1 },
    [VMCU_IID_STDZ]    = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 2, .n_words = 1 },
    [VMCU_IID_STDZQ]   = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 2, .n_words = 1 },
    [VMCU_IID_STS]     = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 2, .n_words = 1 },
    [VMCU_IID_STS32]   = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 2, .n_words = 2 },
    [VMCU_IID_LDS]     = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 2, .n_words = 1 },
    [VMCU_IID_LDS32]   = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 2, .n_words = 2 },
    [VMCU_IID_XCH]     = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 2, .n_words = 1 },
    [VMCU_IID_BRNE]    = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 1, .n_words = 1 },
    [VMCU_IID_BREQ]    = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 1, .n_words = 1 },
    [VMCU_IID_BRGE]    = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 1, .n_words = 1 },
    [VMCU_IID_BRPL]    = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 1, .n_words = 1 },
    [VMCU_IID_BRLO]    = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 1, .n_words = 1 },
    [VMCU_IID_BRLT]    = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 1, .n_words = 1 },
    [VMCU_IID_BRCC]    = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 1, .n_words = 1 },
    [VMCU_IID_BRVS]    = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 1, .n_words = 1 },
    [VMCU_IID_BRTS]    = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 1, .n_words = 1 },
    [VMCU_IID_BRTC]    = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 1, .n_words = 1 },
    [VMCU_IID_BRMI]    = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 1, .n_words = 1 },
    [VMCU_IID_BRHC]    = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 1, .n_words = 1 },
    [VMCU_IID_BRHS]    = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 1, .n_words = 1 },
    [VMCU_IID_BRID]    = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 1, .n_words = 1 },
    [VMCU_IID_BRIE]    = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 1, .n_words = 1 },
    [VMCU_IID_BRVC]    = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 1, .n_words = 1 },
    [VMCU_IID_RCALL]   = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 1, .n_words = 1 },
    [VMCU_IID_RET]     = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 0, .n_words = 1 },
    [VMCU_IID_RETI]    = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 0, .n_words = 1 },
    [VMCU_IID_ICALL]   = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 0, .n_words = 1 },
    [VMCU_IID_CALL]    = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 1, .n_words = 2 },
    [VMCU_IID_CP]      = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 2, .n_words = 1 },
    [VMCU_IID_CPI]     = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 2, .n_words = 1 },
    [VMCU_IID_CPC]     = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 2, .n_words = 1 },
    [VMCU_IID_LSR]     = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 1, .n_words = 1 },
    [VMCU_IID_ASR]     = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 1, .n_words = 1 },
    [VMCU_IID_ROR]     = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 1, .n_words = 1 },
    [VMCU_IID_SWAP]    = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 1, .n_words = 1 },
    [VMCU_IID_ORI]     = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 2, .n_words = 1 },
    [VMCU_IID_OR]      = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 2, .n_words = 1 },
    [VMCU_IID_AND]     = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 2, .n_words = 1 },
    [VMCU_IID_ANDI]    = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 2, .n_words = 1 },
    [VMCU_IID_LAS]     = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 2, .n_words = 1 },
    [VMCU_IID_LAC]     = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 2, .n_words = 1 },
    [VMCU_IID_LAT]     = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 2, .n_words = 1 },
    [VMCU_IID_COM]     = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 1, .n_words = 1 },
    [VMCU_IID_NEG]     = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 1, .n_words = 1 },
    [VMCU_IID_BLD]     = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 2, .n_words = 1 },
    [VMCU_IID_BST]     = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 2, .n_words = 1 },
    [VMCU_IID_SBI]     = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 2, .n_words = 1 },
    [VMCU_IID_CBI]     = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 2, .n_words = 1 },
    [VMCU_IID_LPM]     = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 0, .n_words = 1 },
    [VMCU_IID_LPMZ]    = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 2, .n_words = 1 },
    [VMCU_IID_LPMZI]   = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 2, .n_words = 1 },
    [VMCU_IID_EICALL]  = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 0, .n_words = 1 },
    [VMCU_IID_EIJMP]   = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 0, .n_words = 1 },
    [VMCU_IID_ELPM]    = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 0, .n_words = 1 },
    [VMCU_IID_ELPMZ]   = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 2, .n_words = 1 },
    [VMCU_IID_ELPMZI]  = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 2, .n_words = 1 },
    [VMCU_IID_DES]     = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 1, .n_words = 1 },
    [VMCU_IID_SLEEP]   = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 0, .n_words = 1 },
    [VMCU_IID_WDR]     = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 0, .n_words = 1 },
    [VMCU_IID_BREAK]   = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 0, .n_words = 1 },
    [VMCU_IID_SPM]     = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 0, .n_words = 1 },
    [VMCU_IID_SPMZI]   = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 1, .n_words = 1 },
    [VMCU_IID_SES]     = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 0, .n_words = 1 },
    [VMCU_IID_SET]     = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 0, .n_words = 1 },
    [VMCU_IID_SEV]     = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 0, .n_words = 1 },
    [VMCU_IID_SEZ]     = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 0, .n_words = 1 },
    [VMCU_IID_SEH]     = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 0, .n_words = 1 },
    [VMCU_IID_SEC]     = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 0, .n_words = 1 },
    [VMCU_IID_SEI]     = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 0, .n_words = 1 },
    [VMCU_IID_SEN]     = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 0, .n_words = 1 },
    [VMCU_IID_CLS]     = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 0, .n_words = 1 },
    [VMCU_IID_CLT]     = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 0, .n_words = 1 },
    [VMCU_IID_CLV]     = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 0, .n_words = 1 },
    [VMCU_IID_CLZ]     = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 0, .n_words = 1 },
    [VMCU_IID_CLH]     = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 0, .n_words = 1 },
    [VMCU_IID_CLC]     = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 0, .n_words = 1 },
    [VMCU_IID_CLI]     = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 0, .n_words = 1 },
    [VMCU_IID_CLN]     = { .handler = assemble_nop, .handler_unpacked = pack_and_assemble_nop, .n_operands = 0, .n_words = 1 }
};

/* --- Exposed --- */

asm_table_entry_t* get_asm_table_entry(const vmcu_iid_t iid) {

    if ((iid <= VMCU_IID_ENUM_START) || (iid >= VMCU_IID_ENUM_END))
        return NULL;

    return &asm_table[iid];
}
